/* Beyond the Blueprint — quiz bank
   Every question is answerable from the story text itself.
   a = index of the correct option. */
window.QUIZ = {
  1: [
    { q: "In “The Acidic Echo”, what dose did the operator actually begin preparing?",
      o: ["4 to 5 litres of acid", "425 litres of acid", "45 litres of acid", "4.25 litres of acid"], a: 1,
      why: "“Four to five” became “four hundred and twenty-five” in his mind — 425 litres." },
    { q: "Who prevented the accident in “The Acidic Echo”?",
      o: ["The shift in-charge", "The union leader", "The plant manager, walking by", "A safety alarm"], a: 2,
      why: "The plant manager happened to walk past and spotted the alarming setup." },
    { q: "Why did the mock fire drill turn into a real emergency?",
      o: ["The extinguishers were empty", "A High Tension cable overhead was missed", "The fire team never arrived on site", "The oil container was too large"], a: 1,
      why: "The team lit the oil without noticing an HT cable passing directly overhead." },
    { q: "How did the supervisor escape the union's demand for an apology?",
      o: ["He apologised publicly", "He claimed they misheard “Tala” (lock) as “Saala”", "He called security", "He blamed the workman's goggles"], a: 1,
      why: "He reframed the insult as a concern about the missing lock on the man's locker." },
    { q: "What did the HOD tell the Plant Manager who said “Only God knows why”?",
      o: ["To file a written report", "To go find a temple and not return without a root cause", "To shut the plant immediately", "To call the pump vendor"], a: 1,
      why: "“If only God knows the solution, go find a temple. Don't come back here until you have a root cause.”" }
  ],
  2: [
    { q: "Why wouldn't the senior technician pick up the trash himself?",
      o: ["He hadn't noticed it", "He was forbidden by the union", "Greatness at the top reads as mere duty at the bottom", "He was holding a vacuum pump"], a: 2,
      why: "The same act is read as humility from the MD and as assigned duty from a technician." },
    { q: "What did the HOD offer the disobedient fitter in “Nobody Is Indispensable”?",
      o: ["A promotion", "A fully paid month's leave", "A transfer to another plant", "A written warning"], a: 1,
      why: "A month's paid leave — with an invitation to call and ask whether the company had shut down without him." },
    { q: "In “The Fool on Top”, why did the GM say a fool could do his own job?",
      o: ["Because he had little to do", "Because his decisions rest on summaries the field person prepares", "Because the board made all decisions", "Because he was retiring soon"], a: 1,
      why: "He can approve a wrong report; only the field person can stop the mistake before it reaches him." },
    { q: "How was the sales officer who reported the suspicious discount finally removed?",
      o: ["He was made redundant", "He was trapped over a Second AC travel bill", "He resigned voluntarily", "He was transferred abroad"], a: 1,
      why: "There was no Second AC coach on that train — the whole trip was an elaborate trap." },
    { q: "What did the owner do when a guard demanded he deposit his fountain pen?",
      o: ["Had the guard dismissed", "Ignored him and walked on", "Deposited the pen and later rewarded the guard Rs. 1000", "Complained to the MD"], a: 2,
      why: "He waved off the intervening officers, complied, and rewarded the guard's honesty." }
  ],
  3: [
    { q: "Why was the young chemical engineer speechless at the HCl furnace?",
      o: ["The furnace had failed", "Hydrogen and Chlorine burn without any oxygen entry", "The operator outranked him", "The valves were mislabelled"], a: 1,
      why: "His textbook rule that combustion requires oxygen didn't cover the properties of chlorine." },
    { q: "How did two technicians solve the sprung furnace coils?",
      o: ["With a crane", "With a simple tie-rod", "By cutting new coils", "By heating the coil ends"], a: 1,
      why: "They bridged the three-metre gap with a tie-rod and pulled the coils into position during lunch." },
    { q: "Why did the 86-year-old Director reject the Variable Frequency Drive proposal?",
      o: ["The payback was too slow", "He planned to run at full capacity and hold stock for the cycle", "The drives were imported", "The plant was closing"], a: 1,
      why: "He judged the market to be cyclic — and within six months rates tripled." },
    { q: "What was the mysterious “pipe” the trainee could not trace?",
      o: ["A steam line", "A drain", "The motor's power cable", "A nitrogen purge line"], a: 2,
      why: "It ran from the chlorine compressor motor into the Electrical DB Room — because it was a cable." },
    { q: "Why did the guards' salt samples always pass the lab test?",
      o: ["The lab equipment was faulty", "Truck drivers handed over a clean bag of high-quality salt as “the sample”", "The magnesium test was discontinued", "The guards never sampled at all"], a: 1,
      why: "The drivers supplied their own pre-selected sample — the real cargo was never tested." },
    { q: "What impossibility did the workshop fitter set the engineers?",
      o: ["Lifting a coil without a crane", "Five equidistant holes using only an unmarked ruler and compass", "Welding without power", "Measuring vacuum without a gauge"], a: 1,
      why: "The team chased it for nearly six months before realising it was mathematically impossible." }
  ],
  4: [
    { q: "Why was the security guard in the stronger position against the GM of Finance?",
      o: ["He had union backing", "He was ex-Army with a pension and nothing to lose", "He held a management grade", "He was the owner's relative"], a: 1,
      why: "A secure fallback — pension, and a thousand guard jobs available — left him nothing to lose." },
    { q: "What did the visiting German engineer notice about the workforce?",
      o: ["They worked too fast", "There were assigned times for everything except working", "They lacked tools", "They worked without safety gear"], a: 1,
      why: "Tea, breakfast, lunch and changing clothes all had assigned times — work did not." },
    { q: "How did the Factory Manager disarm the union over the bad tea?",
      o: ["He ordered new tea", "He praised it as fantastic and asked to drink it daily", "He refused to drink it", "He punished the canteen contractor"], a: 1,
      why: "By refusing to be offended, he took away their only weapon." },
    { q: "What finally broke the worker who refused all work?",
      o: ["A pay cut", "Being given no work at all", "A disciplinary transfer", "A union warning"], a: 1,
      why: "Total irrelevance — by week's end he submitted a written apology and begged for a task." }
  ],
  5: [
    { q: "How did the veteran supervisor answer the new graduate's question about his age?",
      o: ["“Old enough to know better”", "“When you were still in liquid form, I was already in uniform”", "“Guess, and you will be wrong”", "“Older than this plant”"], a: 1,
      why: "A single line that placed an ocean of service between them." },
    { q: "What gave away the colleague who denied using foul language?",
      o: ["A recording", "He asked for the names of “the two idiots and lunatics” who complained", "A witness statement", "His own written apology"], a: 1,
      why: "His habit revealed itself the moment his guard dropped at the door." },
    { q: "How did the subordinate reply to the boss who threatened to eat him alive?",
      o: ["He apologised", "He resigned on the spot", "“You will never be able to digest me”", "He called HR"], a: 2,
      why: "Power can consume, but it cannot control the consequences of its own appetite." },
    { q: "Why did the Operation Head say the sharks wouldn't eat the General Manager?",
      o: ["Because he could swim", "Because sharks never eat waste", "Because he would be rescued first", "Because he outranked them"], a: 1,
      why: "A pointed reply to an impossible three-day commissioning deadline." },
    { q: "How did Mr. X handle being knocked to the floor by a worker?",
      o: ["He filed a complaint", "He gave the man a hundred-rupee note and told him to say nothing", "He called security", "He had the man suspended"], a: 1,
      why: "The cost of saving his image was cheaper than the cost of exercising his ego." },
    { q: "What did the boastful GM claim when told of a hundred-year-old banyan tree?",
      o: ["That he had it surveyed", "“I planted it”", "That it should be cut down", "That he had never seen it"], a: 1,
      why: "The habit of claiming credit eventually claimed credit for something that predated him." }
  ],
  6: [
    { q: "Why did the contractor invoice the GM ten rupees?",
      o: ["For a late payment charge", "For passing him a notebook", "For travel to the office", "For a photocopy"], a: 1,
      why: "“I will do any work you ask — but I never work for free.”" },
    { q: "How did the entrepreneur selling below cost end up with one million rupees?",
      o: ["Economies of scale", "Tax rebates", "He started with one billion", "Government subsidy"], a: 2,
      why: "You can't “volume” your way out of a fundamentally loss-making business." },
    { q: "What decides the taxi fare in “Your Problem, My Opportunity”?",
      o: ["Distance travelled", "The meter", "Who is more desperate at that moment", "Time of booking"], a: 2,
      why: "1 AM in the rain with one taxi, versus 11 AM in the sun with fifty." },
    { q: "What made one supermarket busier than twenty-five rivals?",
      o: ["Lower prices", "Trust extended to a stranger without proof", "Home delivery", "Longer opening hours"], a: 1,
      why: "He handed the customer five hundred rupees and refused to note it in his register." },
    { q: "How was the “theft” penalty on the electricity bill resolved?",
      o: ["It was paid in full", "The rulebook capped the penalty at Rs. 600", "The meter was replaced", "The case went to court"], a: 1,
      why: "The scenario wasn't classified as theft at all; the correct penalty was Rs. 600." }
  ],
  7: [
    { q: "Why did the officer abandon the family-planning procedure?",
      o: ["The clinic was closed", "He claimed the eighth child always has the most potential", "His wife refused", "Management withdrew the pressure"], a: 1,
      why: "Logic can be used to justify any desire, however much it contradicts the plan." },
    { q: "Why did cutting chapatis fail to help the pre-diabetic labourer?",
      o: ["He ate extra rice", "He simply made each chapati thicker", "He skipped the medicine", "He miscounted"], a: 1,
      why: "The wheat quantity never changed — only the count did." },
    { q: "What did the grandmother do with “fill it up to the neck”?",
      o: ["Filled the medicine bottle", "Heated a hundred litres in a drum reaching the baby's neck", "Called another doctor", "Diluted the powder in a cup"], a: 1,
      why: "The water only needed to fill the medicine bottle to its own neck." },
    { q: "Why was the resident doctor prescribing the same medicine to everyone?",
      o: ["It was the only stock available", "He'd received a free cupboard from a pharma company", "It was a government directive", "The pharmacist insisted"], a: 1,
      why: "A free cupboard ended up costing every patient in the queue their health." }
  ],
  8: [
    { q: "How did the seven-year tenth-grader answer his teacher's insult?",
      o: ["He apologised", "He compared his years in tenth grade to the teacher's career", "He switched off the radio", "He left the class"], a: 1,
      why: "Sometimes experience is about how long you can survive at the bottom." },
    { q: "What did the scholar-son conclude was in the astrologer's fist?",
      o: ["A black insect", "A coin", "An elephant", "Nothing at all"], a: 2,
      why: "Living, black, two eyes, four legs — therefore, an elephant." },
    { q: "How did the peon report the time from the pendulum clock?",
      o: ["He read it correctly", "“Small needle at twelve, big needle at one” — and swung his arm for the third", "He guessed the hour", "He refused to check"], a: 1,
      why: "An honest literal description, far more entertaining than the answer needed." },
    { q: "What was the unexpected outcome of the badly prepared cheelam?",
      o: ["The boy was expelled", "The Principal's hospital stay cured his addiction", "The chair was replaced", "Nothing changed"], a: 1,
      why: "The clumsiest attempt at the task did more good than the task ever could." },
    { q: "Why did the teacher nominate the ninth-class boy for the Independence Day speech without warning?",
      o: ["No one else volunteered", "He wanted the boy's natural talent to come out on its own", "It was a punishment", "The anchor made a mistake"], a: 1,
      why: "The boy recited a humorous poem instead — and lost his stage fear for good." }
  ],
  9: [
    { q: "What had the labourer actually been eating for fifteen days?",
      o: ["Sattu", "Raw wheat flour", "Jaggery", "Nothing at all"], a: 1,
      why: "He had been eating aata raw, believing it was sattu, for a full fortnight." },
    { q: "What was the truth about the truck driver's brakes and morning drug?",
      o: ["Both were as bad as he said", "Both were inventions — he was testing their nerve", "The brakes failed later", "He was replaced mid-journey"], a: 1,
      why: "Brakes were fine and he'd taken nothing; the friend swore off trucks anyway." },
    { q: "What turned out to be the “ghost” near the haunted temple?",
      o: ["A white bull", "Three farmers with a stuck fertiliser cart", "A lantern on a post", "A wedding party"], a: 1,
      why: "Their white cloths glowed faintly in the lantern light." },
    { q: "Why did Mr. X call his children's lack of degrees a matter of joy?",
      o: ["Degrees cost too much", "They remain dependent on him and care for him always", "He disliked schools", "They joined his business"], a: 1,
      why: "Success can be measured by more than one kind of return on investment." },
    { q: "How was the old lady's slipped disc cured?",
      o: ["By the district hospital", "By the jolts of the train shunting", "By a village remedy", "By rest alone"], a: 1,
      why: "The shunting motion corrected it on the spot — before she ever reached the hospital." },
    { q: "How did the bride's family handle running out of the main vegetable?",
      o: ["They cooked more quickly", "They announced a dog had touched it and asked permission to serve", "They served it anyway", "They delayed the feast"], a: 1,
      why: "Every guest declined at once — an embarrassing shortage became their own gracious decision." }
  ],
  10: [
    { q: "How did Bhuma get his revenge two years later?",
      o: ["He filed a police case", "A staged “mantra and bucket” test marked his enemy as the thief", "He fought him publicly", "He spread a rumour"], a: 1,
      why: "Revenge is a dish that tastes better when it is cold." },
    { q: "Why was the broken window repaired immediately?",
      o: ["A maintenance schedule", "The letter's courteous veiled threat about “any future incident”", "The tenant paid for it", "A manager's inspection"], a: 1,
      why: "A veiled threat wrapped in polite language beat any direct complaint." },
    { q: "How did the senior settle the Rs. 120 restaurant bill?",
      o: ["He paid from his own pocket", "He counted the shopkeeper's own 20-rupee note as a contribution", "He left an IOU", "He washed dishes"], a: 1,
      why: "He made the lender part of the solution — and the shopkeeper laughed and let them go." },
    { q: "Why did the conductor let the adamant passenger travel free?",
      o: ["The passenger had a pass", "He had sworn an oath to issue no ticket that trip", "The tickets ran out", "He feared a complaint"], a: 1,
      why: "He would rather lose the money than break his oath." },
    { q: "How did the hawker disarm the troublemaker offering shoes?",
      o: ["He ran away", "“You may give me only as many as you have received from someone else”", "He called the police", "He offered free sweets"], a: 1,
      why: "A calm, clever answer disarmed the threat and drew the crowd's laughter." }
  ],
  11: [
    { q: "How did the employee explain a second claim for his mother's death?",
      o: ["A clerical error", "His father had five wives — all his mothers", "It was his mother-in-law", "He withdrew the claim"], a: 1,
      why: "Company policy rarely accounts for the complexities of a large family tree." },
    { q: "How did the President block politically imposed candidates?",
      o: ["He refused them outright", "He sent them to Security for a warm welcome and a permanent file", "He created unpaid roles", "He referred them to HR"], a: 1,
      why: "A warm welcome is the most polite way to show someone the door." },
    { q: "What was HR's answer to the veteran outraged by the new recruit's equal pay?",
      o: ["A retention bonus", "A shirt that cost Rs. 50 fourteen years ago now costs Rs. 500", "A promotion", "A transfer"], a: 1,
      why: "The shirt hasn't changed — the market price has." },
    { q: "Why did one officer refuse to raise his hand for “loyal to the company”?",
      o: ["He was resigning", "He is loyal to his work, not the logo", "He had a grievance", "He misheard the question"], a: 1,
      why: "A professional serves the craft; the craft happens to be at that company for now." },
    { q: "How did the contractor “reduce” his 40-strong workforce by twenty percent?",
      o: ["He cut hours instead", "He removed six men and hired the same number of women", "He used subcontractors", "He did nothing at all"], a: 1,
      why: "An instruction taken literally can be obeyed completely and accomplish nothing." }
  ],
  12: [
    { q: "Why did the father demand an apology from the man who slapped his smoking son?",
      o: ["The boy wasn't smoking", "The beedi wasn't bought with the stranger's money", "The stranger was a neighbour", "The boy was older than he looked"], a: 1,
      why: "The story turns from the slap to the system that sells the harm and prints a warning beside it." },
    { q: "What standing instruction kept the ghost permanently occupied?",
      o: ["Guarding the house", "Climbing up and down a pole when idle", "Counting grain", "Fetching water"], a: 1,
      why: "The closing question: are we not sometimes that ghost, busy on repetitive, unnecessary work?" },
    { q: "What does the closing reflection say an organization ends up manufacturing when it fears idle hands more than idle purpose?",
      o: ["Profit", "Busyness instead of value", "Loyalty", "Overtime"], a: 1,
      why: "Busyness instead of value — the book's final warning." }
  ]
};
